export const FETCH_CASES = 'fetch_cases'
export const FETCH_FEATURED_CASES = 'fetch_featured_cases'
export const ADD_CASE = 'add_case'
export const UPDATE_CASE = 'update_case'
export const DELETE_CASE = 'delete_case'
export const LOGIN_USER = 'login_user'
export const LOGOUT_USER = 'logout_user'
export const CURRENT_USER = 'current_user'